<h1> Contact</h1>
<p style="margin-left: 40px; margin-right: 40px"></p>

<form action="/about/contact" method="post" id="contact_form" style="width: 500px; margin-left: 50px">                        
    <p>
        <label for="name">Name</label>
        <input type="text" id="name" name="name" class="round custom-width-input required" required/>
    </p>
    <p>
        <label for="email">Email</label>
        <input type="text" id="email" name="email" class="round custom-width-input required" required/>
    </p>
    <p>
        <label for="subject">Subject</label>
        <input type="text" id="subject" name="subject" class="round custom-width-input required" required/>
    </p>
    <p>
        <label for="message">Message</label>
        <textarea id="message" name="message" class="round" style="width: 350px; height: 100px" required/></textarea>
    </p>    
    <input type="submit" value="Submit" class="round blue ic-up-circle effect2" />

</form>
